/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controllers.ControllerUsers;
import Model.User;
import javax.swing.JTextField;
import Singleton.Singleton;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class GeneralAdmin_CRUD_ReadBoxUsers extends javax.swing.JFrame {

    private ControllerUsers controllerUsers;

    ////////////////////////////////

    private int idPerson;


    /**
     * Creates new form GeneralAdmin_ReadBoxUsers
     */
    public GeneralAdmin_CRUD_ReadBoxUsers() {

        //controllerUsers = Singleton.getInstance().getControllerUser();
        controllerUsers = new ControllerUsers();
        initComponents();
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    private void createAccess() {

        idPerson = Integer.parseInt(txt_ReadUser.getText());

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_ReadUser = new javax.swing.JTextField();
        btn_readUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Digite la cedula");

        btn_readUser.setText("Buscar");
        btn_readUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_readUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ReadUser, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btn_readUser)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txt_ReadUser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btn_readUser)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_readUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_readUserActionPerformed
        createAccess();
        User answer = controllerUsers.readUsers(idPerson);
        if (answer != null) {

            GeneralAdmin_CRUD_Users generalAdmin_CRUD_Users = new GeneralAdmin_CRUD_Users();

            generalAdmin_CRUD_Users.getTxt_NamePerson().setText(answer.getNamePerson());
            generalAdmin_CRUD_Users.getTxt_LastNamePerson().setText(answer.getLastNamePerson());
            generalAdmin_CRUD_Users.getTxt_PasswordUser().setText(answer.getPassword());
            generalAdmin_CRUD_Users.getTxt_UserPerson().setText(answer.getNameUser());
            generalAdmin_CRUD_Users.getTxt_idPerson().setText(Integer.toString(answer.getIdPerson()));
            this.setVisible(false);

        } else {

            JOptionPane.showMessageDialog(null, "El usuario: " + idPerson + " no se encuentra registrado :c");

        }


    }//GEN-LAST:event_btn_readUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralAdmin_CRUD_ReadBoxUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralAdmin_CRUD_ReadBoxUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralAdmin_CRUD_ReadBoxUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralAdmin_CRUD_ReadBoxUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralAdmin_CRUD_ReadBoxUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_readUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_ReadUser;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxt_ReadUser() {
        return txt_ReadUser;
    }

    public void setTxt_ReadUser(JTextField txt_ReadUser) {
        this.txt_ReadUser = txt_ReadUser;
    }
}
