/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controllers.ControllerFlights;
import Controllers.ControllerPlanes;
import Model.AirlineEmployee;
import Model.Flight;
import Model.Plane;
import Singleton.Singleton;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class LogisticsEmployee_CRUD_Flight extends javax.swing.JPanel {

    private String namePlane;
    private String captain;
    private String originFlight;
    private String destineFlight;
    private int day;
    private String month;
    private int year;
    private int hour;
    private int estimateFlight;
    private int idFlight;
    private boolean answer;

    private ControllerFlights controllerFlights;
    private ControllerPlanes controllerPlanes;

    Flight flight;

    ArrayList<AirlineEmployee> listAirlineEmployee;
    ArrayList<Plane> listPlanes;

    /**
     * Creates new form LogisticsEmployee_CRUD_Flight
     */
    public LogisticsEmployee_CRUD_Flight() {
        controllerFlights = new ControllerFlights();
        controllerPlanes = new ControllerPlanes();

        listPlanes = Singleton.getInstance().getListPlane();
        listAirlineEmployee = Singleton.getInstance().getListAirlineEmployee();

        initComponents();

        for (int i = 0; i < listAirlineEmployee.size(); i++) {
            if (listAirlineEmployee.get(i).getPosition().equals("Capitan")) {
                cb2_captainFlight.addItem(listAirlineEmployee.get(i).getNamePerson());
            }

        }

        for (int i = 0; i < listPlanes.size(); i++) {

            cb1_planeFlight.addItem(listPlanes.get(i).getNamePlane());

        }

    }

    private void fullcb() {

    }

    public void cleanSpaces() {///////////////////CleanTxt
        txt_originFlight.setText(null);
        txt_destineFlight.setText(null);
        txt_yearFlight.setText(null);
        txt_estimatedFlight.setText(null);
        txt_idFlight.setText(null);

    }

    private void createAccess() {

        namePlane = cb1_planeFlight.getSelectedItem().toString();
        captain = cb2_captainFlight.getSelectedItem().toString();
        originFlight = txt_originFlight.getText();
        destineFlight = txt_destineFlight.getText();
        day = Integer.parseInt(cb_dayFlight.getSelectedItem().toString());
        month = cb_monthFlight.getSelectedItem().toString();
        year = Integer.parseInt(txt_yearFlight.getText());
        hour = Integer.parseInt(cb_hour.getSelectedItem().toString());
        estimateFlight = Integer.parseInt(txt_estimatedFlight.getText());
        idFlight = Integer.parseInt(txt_idFlight.getText());

        flight = new Flight(namePlane, captain, originFlight, destineFlight, day, month, year, hour, estimateFlight, idFlight);

    }

    private void setAccess(String namePlane, String nameCaptain, String originFlight, String destineFlight, int day, String month, int year, int hour, int estimateFlight, int idFlight) {

        txt_originFlight.setText(originFlight);
        txt_destineFlight.setText(destineFlight);
        txt_yearFlight.setText(Integer.toString(year));
        txt_estimatedFlight.setText(Integer.toString(estimateFlight));
        txt_idFlight.setText(Integer.toString(idFlight));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_createPlane = new javax.swing.JButton();
        btn_UpdatePlane = new javax.swing.JButton();
        btn_readPlane = new javax.swing.JButton();
        btn_deletePlane = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_namePlane = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_StatusPlane = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_idPlane = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_quantitySeats = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_StatusPlane4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn_createFlight = new javax.swing.JButton();
        btn_UpdateFlight = new javax.swing.JButton();
        btn_readFlight = new javax.swing.JButton();
        btn_deleteFlight = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_originFlight = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_destineFlight = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cb1_planeFlight = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_yearFlight = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cb_timeFlight = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txt_estimatedFlight = new javax.swing.JTextField();
        cb_dayFlight = new javax.swing.JComboBox<>();
        cb_monthFlight = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cb_hour = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cb2_captainFlight = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txt_idFlight = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        btn_createPlane.setText("Guardar");
        btn_createPlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createPlaneActionPerformed(evt);
            }
        });

        btn_UpdatePlane.setText("Editar");
        btn_UpdatePlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdatePlaneActionPerformed(evt);
            }
        });

        btn_readPlane.setText("Buscar");
        btn_readPlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_readPlaneActionPerformed(evt);
            }
        });

        btn_deletePlane.setText("Eliminar");
        btn_deletePlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletePlaneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btn_createPlane, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(btn_UpdatePlane, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(btn_readPlane, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btn_deletePlane, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_createPlane, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_UpdatePlane, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_readPlane, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deletePlane, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("nombre avion");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Estado");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Codigo");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Numero asientos");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Mes");

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        btn_createFlight.setText("Guardar");
        btn_createFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createFlightActionPerformed(evt);
            }
        });

        btn_UpdateFlight.setText("Editar");
        btn_UpdateFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateFlightActionPerformed(evt);
            }
        });

        btn_readFlight.setText("Buscar");
        btn_readFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_readFlightActionPerformed(evt);
            }
        });

        btn_deleteFlight.setText("Eliminar");
        btn_deleteFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteFlightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btn_createFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(btn_UpdateFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(btn_readFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btn_deleteFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_createFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_UpdateFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_readFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deleteFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Origen");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Destino");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Avion");

        cb1_planeFlight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        cb1_planeFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1_planeFlightActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("dia");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Mes");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Año");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Hora");

        cb_timeFlight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Am", "Pm" }));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Tiempo estimado");

        cb_dayFlight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31" }));
        cb_dayFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_dayFlightActionPerformed(evt);
            }
        });

        cb_monthFlight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"}));
        cb_monthFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_monthFlightActionPerformed(evt);
            }
        });

        jLabel1.setText("Hrs");

        cb_hour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"1","2","3","4","5","6","7","8","9","10","11","12"}));
        cb_hour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_hourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(cb_hour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cb_timeFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(39, 39, 39)
                                .addComponent(txt_estimatedFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(cb_dayFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_monthFlight, 0, 126, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txt_yearFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(txt_yearFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_dayFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_monthFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cb_timeFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_hour, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txt_estimatedFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1)))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Capitan");

        cb2_captainFlight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        cb2_captainFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2_captainFlightActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("id vuelo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(35, 35, 35)
                            .addComponent(txt_destineFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(35, 35, 35)
                            .addComponent(txt_originFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(35, 35, 35)
                            .addComponent(cb1_planeFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(35, 35, 35)
                            .addComponent(cb2_captainFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel16)
                        .addGap(35, 35, 35)
                        .addComponent(txt_idFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_originFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_destineFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cb1_planeFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cb2_captainFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txt_idFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_createPlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createPlaneActionPerformed

    }//GEN-LAST:event_btn_createPlaneActionPerformed

    private void btn_UpdatePlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdatePlaneActionPerformed

    }//GEN-LAST:event_btn_UpdatePlaneActionPerformed

    private void btn_readPlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_readPlaneActionPerformed

    }//GEN-LAST:event_btn_readPlaneActionPerformed

    private void btn_deletePlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletePlaneActionPerformed

    }//GEN-LAST:event_btn_deletePlaneActionPerformed

    private void btn_createFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createFlightActionPerformed
        createAccess();

        answer = controllerFlights.createFlights(flight);

        if (answer) {

            JOptionPane.showMessageDialog(null, "El vuelo: " + idFlight + " se registró correctamente ");

            cleanSpaces();

        } else {

            JOptionPane.showMessageDialog(null, "Este vuelo ya se encuentra registrado");
        }
    }//GEN-LAST:event_btn_createFlightActionPerformed

    private void btn_UpdateFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateFlightActionPerformed
        createAccess();
        answer = controllerFlights.updateFlights(flight);
        if (answer) {

            JOptionPane.showMessageDialog(null, "Se modificó correctamente c:");

        } else {

            JOptionPane.showMessageDialog(null, "No se modificó >:c");
        }


    }//GEN-LAST:event_btn_UpdateFlightActionPerformed

    private void btn_readFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_readFlightActionPerformed
        flight = controllerFlights.readFlights(idFlight);
        if (flight != null) {

            setAccess(flight.getNamePlane(), flight.getNameCaptain(), flight.getOriginFlight(), flight.getDestineFlight(), flight.getDay(), flight.getMonth(), flight.getYear(), flight.getHour(), flight.getEstimateFlight(), flight.getIdFlight());

        } else {

            JOptionPane.showMessageDialog(null, "No se encontró");
        }

    }//GEN-LAST:event_btn_readFlightActionPerformed

    private void btn_deleteFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteFlightActionPerformed
        createAccess();
        answer = controllerFlights.deleteFlights(flight);
        if (answer) {

            JOptionPane.showMessageDialog(null, "Se elimino correctamente");
            cleanSpaces();

        } else {

            JOptionPane.showMessageDialog(null, "No se eliminó >:o");

        }
    }//GEN-LAST:event_btn_deleteFlightActionPerformed

    private void cb_dayFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_dayFlightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_dayFlightActionPerformed

    private void cb_monthFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_monthFlightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_monthFlightActionPerformed

    private void cb_hourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_hourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_hourActionPerformed

    private void cb1_planeFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1_planeFlightActionPerformed

    }//GEN-LAST:event_cb1_planeFlightActionPerformed

    private void cb2_captainFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2_captainFlightActionPerformed

    }//GEN-LAST:event_cb2_captainFlightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_UpdateFlight;
    private javax.swing.JButton btn_UpdatePlane;
    private javax.swing.JButton btn_createFlight;
    private javax.swing.JButton btn_createPlane;
    private javax.swing.JButton btn_deleteFlight;
    private javax.swing.JButton btn_deletePlane;
    private javax.swing.JButton btn_readFlight;
    private javax.swing.JButton btn_readPlane;
    private javax.swing.JComboBox<String> cb1_planeFlight;
    private javax.swing.JComboBox<String> cb2_captainFlight;
    private javax.swing.JComboBox<String> cb_dayFlight;
    private javax.swing.JComboBox<String> cb_hour;
    private javax.swing.JComboBox<String> cb_monthFlight;
    private javax.swing.JComboBox<String> cb_timeFlight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt_StatusPlane;
    private javax.swing.JTextField txt_StatusPlane4;
    private javax.swing.JTextField txt_destineFlight;
    private javax.swing.JTextField txt_estimatedFlight;
    private javax.swing.JTextField txt_idFlight;
    private javax.swing.JTextField txt_idPlane;
    private javax.swing.JTextField txt_namePlane;
    private javax.swing.JTextField txt_originFlight;
    private javax.swing.JTextField txt_quantitySeats;
    private javax.swing.JTextField txt_yearFlight;
    // End of variables declaration//GEN-END:variables
}
